# Copyright 2024 tison <wander4096@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Copyright 2024 - 2024, tison <wander4096@gmail.com> and the HawkEye contributors
# SPDX-License-Identifier: Apache-2.0

[ACTIONSCRIPT]
pattern = "as"
headerType = "SLASHSTAR_STYLE"
extension = true
filename = false

[ADA_BODY]
pattern = "adb"
headerType = "DOUBLEDASHES_STYLE"
extension = true
filename = false

[ADA_SPEC]
pattern = "ads"
headerType = "DOUBLEDASHES_STYLE"
extension = true
filename = false

[ASCII_DOC]
pattern = "adoc"
headerType = "ASCIIDOC_STYLE"
extension = true
filename = false

[ASP]
pattern = "asp"
headerType = "ASP"
extension = true
filename = false

[ASPECTJ]
pattern = "aj"
headerType = "SLASHSTAR_STYLE"
extension = true
filename = false

[ASSEMBLER]
pattern = "asm"
headerType = "SEMICOLON_STYLE"
extension = true
filename = false

[C]
pattern = "c"
headerType = "SLASHSTAR_STYLE"
extension = true
filename = false

[CC]
pattern = "cc"
headerType = "SLASHSTAR_STYLE"
extension = true
filename = false

[CLOJURE]
pattern = "clj"
headerType = "SEMICOLON_STYLE"
extension = true
filename = false

[CLOJURESCRIPT]
pattern = "cljs"
headerType = "SEMICOLON_STYLE"
extension = true
filename = false

[CMAKELISTS]
pattern = "CMakeLists.txt"
headerType = "SCRIPT_STYLE"
extension = false
filename = true

[COLDFUSION_COMPONENT]
pattern = "cfc"
headerType = "DYNASCRIPT3_STYLE"
extension = true
filename = false

[COLDFUSION_ML]
pattern = "cfm"
headerType = "DYNASCRIPT3_STYLE"
extension = true
filename = false

[CPP]
pattern = "cpp"
headerType = "SLASHSTAR_STYLE"
extension = true
filename = false

[CSHARP]
pattern = "cs"
headerType = "SLASHSTAR_STYLE"
extension = true
filename = false

[CSS]
pattern = "css"
headerType = "SLASHSTAR_STYLE"
extension = true
filename = false

[DELPHI]
pattern = "pas"
headerType = "BRACESSTAR_STYLE"
extension = true
filename = false

[DOCKERFILE]
pattern = "Dockerfile"
headerType = "SCRIPT_STYLE"
extension = false
filename = true

[DOXIA_APT]
pattern = "apt"
headerType = "DOUBLETILDE_STYLE"
extension = true
filename = false

[DOXIA_FAQ]
pattern = "fml"
headerType = "XML_STYLE"
extension = true
filename = false

[DTD]
pattern = "dtd"
headerType = "XML_STYLE"
extension = true
filename = false

[EDITORCONFIG]
pattern = ".editorconfig"
headerType = "SCRIPT_STYLE"
extension = false
filename = true

[EIFFEL]
pattern = "e"
headerType = "DOUBLEDASHES_STYLE"
extension = true
filename = false

[ERLANG]
pattern = "erl"
headerType = "PERCENT3_STYLE"
extension = true
filename = false

[ERLANG_HEADER]
pattern = "hrl"
headerType = "PERCENT3_STYLE"
extension = true
filename = false

[FORTRAN]
pattern = "f"
headerType = "EXCLAMATION_STYLE"
extension = true
filename = false

[FREEMARKER]
pattern = "ftl"
headerType = "FTL"
extension = true
filename = false

[GO]
pattern = "go"
headerType = "SLASHSTAR_STYLE"
extension = true
filename = false

[GO_MOD]
pattern = "go.mod"
headerType = "DOUBLESLASH_STYLE"
extension = false
filename = true

[GRADLE]
pattern = "gradle"
headerType = "SLASHSTAR_STYLE"
extension = true
filename = false

[GROOVY]
pattern = "groovy"
headerType = "SLASHSTAR_STYLE"
extension = true
filename = false

[GSP]
pattern = "GSP"
headerType = "XML_STYLE"
extension = true
filename = false

[H]
pattern = "h"
headerType = "SLASHSTAR_STYLE"
extension = true
filename = false

[HH]
pattern = "hh"
headerType = "SLASHSTAR_STYLE"
extension = true
filename = false

[HPP]
pattern = "hpp"
headerType = "SLASHSTAR_STYLE"
extension = true
filename = false

[HAML]
pattern = "haml"
headerType = "HAML_STYLE"
extension = true
filename = false

[HTM]
pattern = "htm"
headerType = "XML_STYLE"
extension = true
filename = false

[HTML]
pattern = "html"
headerType = "XML_STYLE"
extension = true
filename = false

[JAVA]
pattern = "java"
headerType = "SLASHSTAR_STYLE"
extension = true
filename = false

[JAVAFX]
pattern = "fx"
headerType = "SLASHSTAR_STYLE"
extension = true
filename = false

[JAVASCRIPT]
pattern = "js"
headerType = "SLASHSTAR_STYLE"
extension = true
filename = false

[JSP]
pattern = "jsp"
headerType = "DYNASCRIPT_STYLE"
extension = true
filename = false

[JSPX]
pattern = "jspx"
headerType = "XML_STYLE"
extension = true
filename = false

[JSX]
pattern = "jsx"
headerType = "SLASHSTAR_STYLE"
extension = true
filename = false

[KML]
pattern = "kml"
headerType = "XML_STYLE"
extension = true
filename = false

[KOTLIN]
pattern = "kt"
headerType = "SLASHSTAR_STYLE"
extension = true
filename = false

[KOTLIN_SCRIPT]
pattern = "kts"
headerType = "SLASHSTAR_STYLE"
extension = true
filename = false

[LISP]
pattern = "el"
headerType = "EXCLAMATION3_STYLE"
extension = true
filename = false

[LUA]
pattern = "lua"
headerType = "LUA"
extension = true
filename = false

[MOONBIT]
pattern = "mbt"
headerType = "DOUBLESLASH_STYLE"
extension = true
filename = false

[MUSTACHE]
pattern = "mustache"
headerType = "MUSTACHE_STYLE"
extension = true
filename = false

[MVEL]
pattern = "mv"
headerType = "MVEL_STYLE"
extension = true
filename = false

[MXML]
pattern = "mxml"
headerType = "XML_STYLE"
extension = true
filename = false

[PERL]
pattern = "pl"
headerType = "SCRIPT_STYLE"
extension = true
filename = false

[PERL_MODULE]
pattern = "pm"
headerType = "SCRIPT_STYLE"
extension = true
filename = false

[PHP]
pattern = "php"
headerType = "PHP"
extension = true
filename = false

[POM]
pattern = "pom"
headerType = "XML_STYLE"
extension = true
filename = false

[PROPERTIES]
pattern = "properties"
headerType = "SCRIPT_STYLE"
extension = true
filename = false

[PROTO]
pattern = "proto"
headerType = "SLASHSTAR_STYLE"
extension = true
filename = false

[PYTHON]
pattern = "py"
headerType = "SCRIPT_STYLE"
extension = true
filename = false

[PYTHON_STUBS]
pattern = "pyi"
headerType = "SCRIPT_STYLE"
extension = true
filename = false

[ROBOT_FRAMEWORK]
pattern = "robot"
headerType = "SCRIPT_STYLE"
extension = true
filename = false

[ROBOT_FRAMEWORK_RESOURCE]
pattern = "resource"
headerType = "SCRIPT_STYLE"
extension = true
filename = false

[RUBY]
pattern = "rb"
headerType = "SCRIPT_STYLE"
extension = true
filename = false

[RUST]
pattern = "rs"
headerType = "DOUBLESLASH_STYLE"
extension = true
filename = false

[SCALA]
pattern = "scala"
headerType = "SLASHSTAR_STYLE"
extension = true
filename = false

[SCAML]
pattern = "scaml"
headerType = "HAML_STYLE"
extension = true
filename = false

[SCSS]
pattern = "scss"
headerType = "SLASHSTAR_STYLE"
extension = true
filename = false

[SHELL]
pattern = "sh"
headerType = "SCRIPT_STYLE"
extension = true
filename = false

[SPRING_FACTORIES]
pattern = "spring.factories"
headerType = "SCRIPT_STYLE"
extension = false
filename = false

[SQL]
pattern = "sql"
headerType = "DOUBLEDASHES_STYLE"
extension = true
filename = false

[TAGX]
pattern = "tagx"
headerType = "XML_STYLE"
extension = true
filename = false

[TEX_CLASS]
pattern = "cls"
headerType = "PERCENT_STYLE"
extension = true
filename = false

[TEX_STYLE]
pattern = "sty"
headerType = "PERCENT_STYLE"
extension = true
filename = false

[TEX]
pattern = "tex"
headerType = "PERCENT_STYLE"
extension = true
filename = false

[TLD]
pattern = "tld"
headerType = "XML_STYLE"
extension = true
filename = false

[TOML]
pattern = "toml"
headerType = "SCRIPT_STYLE"
extension = true
filename = false

[TS]
pattern = "ts"
headerType = "SLASHSTAR_STYLE"
extension = true
filename = false

[TSX]
pattern = "tsx"
headerType = "SLASHSTAR_STYLE"
extension = true
filename = false

[VB]
pattern = "bas"
headerType = "HAML_STYLE"
extension = true
filename = false

[VBA]
pattern = "vba"
headerType = "APOSTROPHE_STYLE"
extension = true
filename = false

[VELOCITY]
pattern = "vm"
headerType = "SHARPSTAR_STYLE"
extension = true
filename = false

[WINDOWS_BATCH]
pattern = "bat"
headerType = "BATCH"
extension = true
filename = false

[WINDOWS_SHELL]
pattern = "cmd"
headerType = "BATCH"
extension = true
filename = false

[WSDL]
pattern = "wsdl"
headerType = "XML_STYLE"
extension = true
filename = false

[XHTML]
pattern = "xhtml"
headerType = "XML_STYLE"
extension = true
filename = false

[XML]
pattern = "xml"
headerType = "XML_STYLE"
extension = true
filename = false

[XSD]
pattern = "xsd"
headerType = "XML_STYLE"
extension = true
filename = false

[XSL]
pattern = "xsl"
headerType = "XML_STYLE"
extension = true
filename = false

[XSLT]
pattern = "xslt"
headerType = "XML_STYLE"
extension = true
filename = false

[YAML]
pattern = "yaml"
headerType = "SCRIPT_STYLE"
extension = true
filename = false

[YML]
pattern = "yml"
headerType = "SCRIPT_STYLE"
extension = true
filename = false

[ZIG]
pattern = "zig"
headerType = "DOUBLESLASH_STYLE"
extension = true
filename = false
